//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.20 at 06:44:57 PM EST 
//


package edu.stevens.cs.cs548.clinic.reps;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.stevens.cs.cs548.clinic.reps package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Treatment_QNAME = new QName("http://www.example.org/Clinic/Treatment", "treatment");
    private final static QName _Patient_QNAME = new QName("http://www.example.org/Clinic/Treatment", "patient");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.stevens.cs.cs548.clinic.reps
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RadiologyType }
     * 
     */
    public RadiologyType createRadiologyType() {
        return new RadiologyType();
    }

    /**
     * Create an instance of {@link PatientType.Treatments }
     * 
     */
    public PatientType.Treatments createPatientTypeTreatments() {
        return new PatientType.Treatments();
    }

    /**
     * Create an instance of {@link DrugTreatmentType }
     * 
     */
    public DrugTreatmentType createDrugTreatmentType() {
        return new DrugTreatmentType();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientRepresentation();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link SurgeryType }
     * 
     */
    public SurgeryType createSurgeryType() {
        return new SurgeryType();
    }

    /**
     * Create an instance of {@link TreatmentType }
     * 
     */
    public TreatmentType createTreatmentType() {
        return new TreatmentRepresentation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TreatmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Clinic/Treatment", name = "treatment")
    public JAXBElement<TreatmentType> createTreatment(TreatmentType value) {
        return new JAXBElement<TreatmentType>(_Treatment_QNAME, ((Class) TreatmentRepresentation.class), null, ((TreatmentRepresentation) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Clinic/Treatment", name = "patient")
    public JAXBElement<PatientType> createPatient(PatientType value) {
        return new JAXBElement<PatientType>(_Patient_QNAME, ((Class) PatientRepresentation.class), null, ((PatientRepresentation) value));
    }

}
